
// This file is automatically generated. Do not modify.
export const firebaseConfig = {
  "projectId": "studio-3954880650-2d317",
  "appId": "1:196481164228:web:246ab9c3575d4717097a91",
  "apiKey": "AIzaSyAKhZX8IZ2VIG2xi-ONfMYjjdf1efd5CVk",
  "authDomain": "studio-3954880650-2d317.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "196481164228",
  "databaseURL": "https://studio-3954880650-2d317-default-rtdb.firebaseio.com"
};
