compatibility_date = "2025-09-21"

name = "bloks-io"
type = "javascript"

[assets]
directory = "./.next"

[env.production]
account_id = "e3a2bc8889403d14e3a1f6dc96bd2fc7"
workers_dev = true 
zone_id = ""

[build]
command = "npm run build"
